# Generated by Django 4.0.4 on 2022-05-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_management', '0002_ejecucion_rename_esproduccion_spider_es_produccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucion',
            name='sitio_web',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping_management.sitioweb'),
        ),
    ]
