# Generated by Django 4.0.4 on 2022-05-15 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_management', '0003_ejecucion_sitio_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucion',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraping_management.categoria'),
        ),
        migrations.AlterField(
            model_name='sitioweb',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
