# Generated by Django 4.0.4 on 2022-05-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_management', '0004_alter_ejecucion_categoria_alter_sitioweb_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('precio', models.FloatField()),
                ('divisa', models.CharField(max_length=10)),
                ('fecha_extraccion', models.DateTimeField()),
                ('ejecucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping_management.ejecucion')),
            ],
        ),
    ]
