# Generated by Django 4.0.4 on 2022-05-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_management', '0005_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='url_image',
            field=models.URLField(default='none'),
            preserve_default=False,
        ),
    ]
